<h1>Single Layer Perceptron</h1>

In [18]:
import numpy as np
import pandas as pd

In [19]:
x = np.array([[1, 1, 1, 1], 
              [-1, 1, -1, -1],
              [1, 1, 1, -1],
              [1, -1, -1, 1]])
x

array([[ 1,  1,  1,  1],
       [-1,  1, -1, -1],
       [ 1,  1,  1, -1],
       [ 1, -1, -1,  1]])

In [20]:
x.shape

(4, 4)

In [21]:
samples, features = x.shape

In [22]:
t = np.ones(samples)
t

array([1., 1., 1., 1.])

In [23]:
for i in range(samples):
 if -1 in x[i]:
    t[i] = -1
t

array([ 1., -1., -1., -1.])

In [24]:
w = np.zeros(features)
w

array([0., 0., 0., 0.])

In [25]:
b = 0
alpha = 1

<h4>Activation Function</h4>

In [26]:
def activation_func(y_in):
 if y_in > 0: 
    return 1
 elif y_in == 0: 
    return 0
 else: 
    return -1

<h4>Creating Perceptron</h4>

In [27]:
iterations = pd.DataFrame()
iterations[['x1','x2','x3','x4','t','y_in','y','w1','w2','w3','w4','b']] = None

In [28]:
def perceptron(x,samples,features,t,w,b,alpha,epochs,iterations):
    for epoch in range(1,epochs+1):
        itr_x = []
        itr_w = []
        for id, x_i in enumerate(x):
            y_in = np.dot(x_i,w.T) + b
            y = activation_func(y_in)
            if y!= t[id]:
                for i in range(features):
                    w[i] = w[i] + alpha*t[id]*x_i[i];
                b = b + alpha*t[id]
            itr_x.extend(x_i)
            itr_w.extend(w)
            row = []
            row.extend(itr_x)
            row.append(t[id])
            row.append(y_in)
            row.append(y)
            row.extend(itr_w)
            row.append(b)
            iterations.loc[len(iterations.index)] = row
            row.clear()
            itr_x.clear()
            itr_w.clear()
        print('Iteration',epoch)
        print(iterations)
        iterations = iterations[0:0]
    return w,b


In [29]:
w,b = perceptron(x,samples,features,t,w,b,alpha,2,iterations)

Iteration 1
    x1   x2   x3   x4    t  y_in    y   w1   w2   w3   w4    b
0  1.0  1.0  1.0  1.0  1.0   0.0  0.0  1.0  1.0  1.0  1.0  1.0
1 -1.0  1.0 -1.0 -1.0 -1.0  -1.0 -1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0 -1.0 -1.0   3.0  1.0  0.0  0.0  0.0  2.0  0.0
3  1.0 -1.0 -1.0  1.0 -1.0   2.0  1.0 -1.0  1.0  1.0  1.0 -1.0
Iteration 2
    x1   x2   x3   x4    t  y_in    y   w1   w2   w3   w4    b
0  1.0  1.0  1.0  1.0  1.0   1.0  1.0 -1.0  1.0  1.0  1.0 -1.0
1 -1.0  1.0 -1.0 -1.0 -1.0  -1.0 -1.0 -1.0  1.0  1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0 -1.0  -1.0 -1.0 -1.0  1.0  1.0  1.0 -1.0
3  1.0 -1.0 -1.0  1.0 -1.0  -3.0 -1.0 -1.0  1.0  1.0  1.0 -1.0


C:\Users\owner\AppData\Local\Temp/ipykernel_17088/2350287618.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iterations.loc[len(iterations.index)] = row
C:\Users\owner\AppData\Local\Temp/ipykernel_17088/2350287618.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iterations.loc[len(iterations.index)] = row
C:\Users\owner\AppData\Local\Temp/ipykernel_17088/2350287618.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iteration

In [30]:
print('Weights: ',w)
print('Bias: ',b)

Weights:  [-1.  1.  1.  1.]
Bias:  -1.0
